# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build-legacy-codes

on:
  push:
    paths:
      - "legacy/**"
    branches:
      - master
  pull_request:
    paths:
      - "legacy/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:

  # The following samples used deprecated APIs and not updated to the latest Quarkus.
  hibernate-reactive-java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Building with Maven
        run: |
          mvn -q clean  package --file legacy/hibernate-reactive-java8/pom.xml -DskipTests

  java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Building with Maven
        run: |
          mvn -q clean  package --file legacy/java8/pom.xml -DskipTests

  rxjava2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Building with Maven
        run: |
          mvn -q clean  package --file legacy/rxjava2/pom.xml -DskipTests

  vertx-routes-java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Building with Maven
        run: |
          mvn -q clean  package --file legacy/vertx-routes-java8/pom.xml -DskipTests
