# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: jms

on:
  push:
    paths:
      - "jms/**"
    branches:
      - master
  pull_request:
    paths:
      - "jms/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "21"
          cache: "maven"
             
      - name: Start up Atemis
        run: |
            docker-compose up -d --file jms/docker-compose.yaml
            docker ps -a        
      - name: Build with Maven
        run: |
          mvn -q clean test --file jms/pom.xml 
