# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: quartz

on:
  push:
    paths:
      - "quartz/**"
    branches:
      - master
  pull_request:
    paths:
      - "quartz/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: "21"
          cache: "maven"
          
      - name: Start up databases via Docker Compose 
        run: |
            docker-compose up -d postgres
            docker ps -a        
      - name: Build with Maven
        run: |
          cd quartz
          chmod +x mvnw
          ./mvnw -q clean package -DskipTests
