# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: resteasy-classic

on:
  push:
    paths:
      - "resteasy-classic/**"
    branches:
      - master
  pull_request:
    paths:
      - "resteasy-classic/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: "maven"
          
      - name: Start up databases via Docker Compose 
        run: |
            docker-compose up -d postgres
            docker ps -a        
      - name: Build with Maven
        run: |
          mvn -q clean  test --file resteasy-classic/pom.xml
