# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: spring

on:
  push:
    paths:
      - "spring/**"
    branches:
      - master
  pull_request:
    paths:
      - "spring/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "21"
          cache: "maven"
               
      - name: Build with Maven
        run: |
          cd spring
          chmod +x mvnw
          ./mvnw -q clean test
